export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCT_ERROR = 'DOWNLOAD_PRODUCT_ERROR';

export const GET_PRODUCT_DELETE = 'GET_PRODUCT_DELETE';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_ERROR = 'PRODUCT_DELETE_ERROR';

export const GET_PRODUCT_EDIT = 'GET_PRODUCT_EDIT';
export const START_EDIT_PRODUCT = 'START_EDIT_PRODUCT';
export const PRODUCT_EDIT_SUCCESS = 'PRODUCT_EDIT_SUCCESS';
export const PRODUCT_EDIT_ERROR = 'PRODUCT_EDIT_ERROR';

export const START_DOWNLOAD_CATEGORIES = 'START_DOWNLOAD_CATEGORIES';
export const DOWNLOAD_CATEGORIES_SUCCESS = 'DOWNLOAD_CATEGORIES_SUCCESS';
export const DOWNLOAD_CATEGORIES_ERROR = 'DOWNLOAD_CATEGORIES_ERROR';

export const START_DOWNLOAD_DEPARTMENTS = 'START_DOWNLOAD_DEPARTMENTS';
export const DOWNLOAD_DEPARTMENTS_SUCCESS = 'DOWNLOAD_DEPARTMENTS_SUCCESS';
export const DOWNLOAD_DEPARTMENTS_ERROR = 'DOWNLOAD_DEPARTMENTS_ERROR';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';

export const GET_CATEGORY_DELETE = 'GET_CATEGORY_DELETE';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_ERROR = 'CATEGORY_DELETE_ERROR';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_ERROR = 'ADD_DEPARTMENT_ERROR';

export const GET_DEPARTMENT_DELETE = 'GET_DEPARTMENT_DELETE';
export const DEPARTMENT_DELETE_SUCCESS = 'DEPARTMENT_DELETE_SUCCESS';
export const DEPARTMENT_DELETE_ERROR = 'DEPARTMENT_DELETE_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';







